server:
  port: 8082
spring:
  application:
    name: EventConsumerService
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: event-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.headers: false
        spring.json.value.default.type: org.example.consumer.model.Event
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: manual
      enable-dlt: true
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27018/mongodb?authSource=admin
