server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5434/notification
  application:
    name:
      NotificationService
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    virtual-host: /
    listener:
      simple:
        concurrency: 6
        max-concurrency: 10
        acknowledge-mode: manual